import { Difficulty } from './guess_output.schema';

interface SeedQuestion {
  q: string;
  o: { a: string; b: string; c: string; d: string };
  c: number;
  ex: string;
  difficulty: Difficulty;
}

export const seedQuestions: SeedQuestion[] = [
  // ===== EASY (25 questions) =====
  {
    q: `What is the output?\nprint(2 + 3)`,
    o: { a: '5', b: '23', c: '6', d: 'Error' },
    c: 0,
    ex: '2 + 3 = 5 in Python. The + operator adds two numbers.',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(type(42))`,
    o: {
      a: "<class 'int'>",
      b: "<class 'float'>",
      c: "<class 'str'>",
      d: "<class 'bool'>",
    },
    c: 0,
    ex: "42 is an integer literal, so type(42) returns <class 'int'>.",
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint('Hello' + ' ' + 'World')`,
    o: { a: 'Hello World', b: 'HelloWorld', c: 'Hello + World', d: 'Error' },
    c: 0,
    ex: 'The + operator concatenates strings. "Hello" + " " + "World" = "Hello World".',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(10 // 3)`,
    o: { a: '3', b: '3.33', c: '3.0', d: '1' },
    c: 0,
    ex: '// is floor division. 10 // 3 = 3 (integer division, truncates toward negative infinity).',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(10 % 3)`,
    o: { a: '1', b: '3', c: '0', d: '10' },
    c: 0,
    ex: '% is the modulo operator. 10 % 3 = 1 (remainder of 10/3).',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(bool(0))`,
    o: { a: 'False', b: 'True', c: '0', d: 'None' },
    c: 0,
    ex: 'bool(0) converts 0 to a boolean. In Python, 0 is falsy, so it returns False.',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(len('Python'))`,
    o: { a: '6', b: '5', c: '7', d: '0' },
    c: 0,
    ex: "len() returns the number of characters. 'Python' has 6 letters.",
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(3 ** 2)`,
    o: { a: '9', b: '6', c: '8', d: '12' },
    c: 0,
    ex: '** is the exponentiation operator. 3 ** 2 = 3^2 = 9.',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint('abc' * 3)`,
    o: { a: 'abcabcabc', b: 'abc3', c: 'abc abc abc', d: 'Error' },
    c: 0,
    ex: 'Multiplying a string by an integer repeats it. "abc" * 3 = "abcabcabc".',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nx = [1, 2, 3]\nprint(len(x))`,
    o: { a: '3', b: '2', c: '4', d: '1' },
    c: 0,
    ex: 'len() returns the number of elements in a list. The list [1, 2, 3] has 3 elements.',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(5 > 3)`,
    o: { a: 'True', b: 'False', c: '5', d: '3' },
    c: 0,
    ex: '5 > 3 is a comparison that evaluates to True (5 is greater than 3).',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint('Python'.upper())`,
    o: { a: 'PYTHON', b: 'python', c: 'Python', d: 'pYTHON' },
    c: 0,
    ex: "The .upper() method converts all characters in a string to uppercase. 'Python' → 'PYTHON'.",
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(2.5 * 2)`,
    o: { a: '5.0', b: '5', c: '4.0', d: '5.5' },
    c: 0,
    ex: '2.5 * 2 = 5.0. Multiplying a float by an int results in a float.',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(list(range(3)))`,
    o: { a: '[0, 1, 2]', b: '[1, 2, 3]', c: '[0, 1, 2, 3]', d: '[1, 2]' },
    c: 0,
    ex: 'range(3) generates numbers 0, 1, 2 (stop is exclusive). list() converts it to [0, 1, 2].',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint('hello'[0])`,
    o: { a: 'h', b: 'e', c: '0', d: 'hello' },
    c: 0,
    ex: "Strings are 0-indexed. 'hello'[0] accesses the first character 'h'.",
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(int(3.9))`,
    o: { a: '3', b: '4', c: '3.0', d: 'Error' },
    c: 0,
    ex: 'int() truncates toward zero. int(3.9) = 3 (the decimal part is dropped).',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(not True)`,
    o: { a: 'False', b: 'True', c: 'None', d: 'Error' },
    c: 0,
    ex: 'not is the logical negation operator. not True = False.',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint('a' in 'apple')`,
    o: { a: 'True', b: 'False', c: 'a', d: 'None' },
    c: 0,
    ex: "The 'in' operator checks if a substring exists. 'a' is in 'apple', so it returns True.",
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nx = None\nprint(x is None)`,
    o: { a: 'True', b: 'False', c: 'None', d: 'Error' },
    c: 0,
    ex: "'is' checks identity. x is None checks if x refers to the None object, which it does, so True.",
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(round(3.14159, 2))`,
    o: { a: '3.14', b: '3.1', c: '3.142', d: '3.0' },
    c: 0,
    ex: 'round(3.14159, 2) rounds to 2 decimal places: 3.14.',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint('123'.isdigit())`,
    o: { a: 'True', b: 'False', c: '123', d: 'None' },
    c: 0,
    ex: ".isdigit() returns True if all characters in the string are digits. '123' contains only digits.",
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(abs(-5))`,
    o: { a: '5', b: '-5', c: '0', d: 'None' },
    c: 0,
    ex: 'abs() returns the absolute value. abs(-5) = 5.',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(min(3, 7, 1))`,
    o: { a: '1', b: '3', c: '7', d: 'None' },
    c: 0,
    ex: 'min() returns the smallest value among the arguments. min(3, 7, 1) = 1.',
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint('hello'.capitalize())`,
    o: { a: 'Hello', b: 'hello', c: 'HELLO', d: 'hELLO' },
    c: 0,
    ex: ".capitalize() converts the first character to uppercase and the rest to lowercase. 'hello' → 'Hello'.",
    difficulty: 'easy',
  },
  {
    q: `What is the output?\nprint(True + True)`,
    o: { a: '2', b: 'True', c: '1', d: 'Error' },
    c: 0,
    ex: 'True is treated as 1 in arithmetic contexts. True + True = 1 + 1 = 2.',
    difficulty: 'easy',
  },

  // ===== MEDIUM (25 questions) =====
  {
    q: `What is the output?\nx = [1, 2, 3]\nx.append(4)\nprint(x)`,
    o: { a: '[1, 2, 3, 4]', b: '[4, 1, 2, 3]', c: '[1, 2, 3]', d: 'Error' },
    c: 0,
    ex: 'list.append(4) adds 4 to the end of the list. The list becomes [1, 2, 3, 4].',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint(type([]))`,
    o: {
      a: "<class 'list'>",
      b: "<class 'array'>",
      c: "<class 'dict'>",
      d: "<class 'tuple'>",
    },
    c: 0,
    ex: "[] is an empty list literal. type([]) returns <class 'list'>.",
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nfor i in range(3):\n    print(i, end=' ')`,
    o: { a: '0 1 2', b: '1 2 3', c: '0 1 2 3', d: '0 1 2 ' },
    c: 0,
    ex: "range(3) yields 0, 1, 2. end=' ' prints a space instead of a newline. Output: '0 1 2'.",
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nx = {1, 2, 2, 3}\nprint(len(x))`,
    o: { a: '3', b: '4', c: '2', d: '1' },
    c: 0,
    ex: 'Sets only contain unique elements. {1, 2, 2, 3} = {1, 2, 3}, so len() = 3.',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint(' '.join(['a', 'b', 'c']))`,
    o: { a: 'a b c', b: 'abc', c: 'a,b,c', d: "['a', 'b', 'c']" },
    c: 0,
    ex: "'.join() concatenates list elements with the separator string. ' '.join(['a','b','c']) = 'a b c'.",
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nx = [1, 2, 3]\ny = x\ny[0] = 99\nprint(x[0])`,
    o: { a: '99', b: '1', c: 'Error', d: 'None' },
    c: 0,
    ex: 'y = x creates a reference, not a copy. Both variables point to the same list, so modifying y also affects x.',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint(3 * 'ab')`,
    o: { a: 'ababab', b: 'ab3', c: '3ab', d: 'Error' },
    c: 0,
    ex: 'Multiplying a string by an integer repeats it. 3 * "ab" = "ababab".',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\ndef foo():\n    return 1\nprint(foo())`,
    o: { a: '1', b: 'None', c: 'foo', d: 'Error' },
    c: 0,
    ex: 'foo() is called and returns 1, which is then printed.',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint(dict(a=1, b=2))`,
    o: {
      a: "{'a': 1, 'b': 2}",
      b: "{1: 'a', 2: 'b'}",
      c: "['a', 1, 'b', 2]",
      d: 'Error',
    },
    c: 0,
    ex: "dict(a=1, b=2) creates a dictionary with string keys 'a' and 'b' mapped to 1 and 2.",
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint(10 / 3)`,
    o: { a: '3.3333333333333335', b: '3', c: '3.33', d: '3.0' },
    c: 0,
    ex: '/ is true division in Python 3. 10 / 3 = 3.3333333333333335 (floating-point result).',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nx = 'hello'\nprint(x[::-1])`,
    o: { a: 'olleh', b: 'hello', c: 'h', d: 'olle' },
    c: 0,
    ex: "[::-1] reverses a sequence using slicing with step -1. 'hello' reversed is 'olleh'.",
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint(2 ** 10)`,
    o: { a: '1024', b: '100', c: '20', d: '512' },
    c: 0,
    ex: '2 ** 10 = 2^10 = 1024.',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nx = [3, 1, 2]\nx.sort()\nprint(x)`,
    o: { a: '[1, 2, 3]', b: '[3, 2, 1]', c: '[3, 1, 2]', d: 'None' },
    c: 0,
    ex: 'list.sort() sorts the list in-place in ascending order. [3, 1, 2] becomes [1, 2, 3].',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint('hello'.count('l'))`,
    o: { a: '2', b: '1', c: '3', d: '0' },
    c: 0,
    ex: ".count('l') counts occurrences of 'l' in the string. 'hello' has two 'l' characters.",
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nx = (1, 2, 3)\nprint(x[1])`,
    o: { a: '2', b: '1', c: '3', d: 'Error' },
    c: 0,
    ex: 'Tuples are 0-indexed like lists. x[1] accesses the second element, which is 2.',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint(list('abc'))`,
    o: { a: "['a', 'b', 'c']", b: 'abc', c: "['abc']", d: 'Error' },
    c: 0,
    ex: "list('abc') converts the string into a list of its characters: ['a', 'b', 'c'].",
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint(0 or 1)`,
    o: { a: '1', b: '0', c: 'True', d: 'False' },
    c: 0,
    ex: 'or returns the first truthy value. 0 is falsy, so it evaluates and returns 1.',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nx = {'a': 1, 'b': 2}\nprint(x.get('c', 0))`,
    o: { a: '0', b: 'None', c: '2', d: 'Error' },
    c: 0,
    ex: "dict.get(key, default) returns the value for 'c' if it exists, otherwise returns the default 0.",
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint(1 and 0)`,
    o: { a: '0', b: '1', c: 'True', d: 'False' },
    c: 0,
    ex: 'and returns the first falsy value or the last value if all are truthy. 1 is truthy, so it returns 0.',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nx = [1, 2, 3]\nprint(x.pop())`,
    o: { a: '3', b: '1', c: '[1, 2]', d: 'Error' },
    c: 0,
    ex: 'list.pop() removes and returns the last element. x.pop() returns 3.',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint('{0} is {1}'.format('Python', 'fun'))`,
    o: { a: 'Python is fun', b: '{0} is {1}', c: 'fun is Python', d: 'Error' },
    c: 0,
    ex: ".format() replaces {0} with the first argument and {1} with the second. Result: 'Python is fun'.",
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint(any([False, True, False]))`,
    o: { a: 'True', b: 'False', c: 'None', d: 'Error' },
    c: 0,
    ex: 'any() returns True if at least one element is truthy. The list contains True, so it returns True.',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint(all([True, True, False]))`,
    o: { a: 'False', b: 'True', c: 'None', d: 'Error' },
    c: 0,
    ex: 'all() returns True only if ALL elements are truthy. False is in the list, so it returns False.',
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nx = '  hello  '\nprint(x.strip())`,
    o: { a: 'hello', b: '  hello  ', c: 'hello  ', d: '  hello' },
    c: 0,
    ex: ".strip() removes leading and trailing whitespace. '  hello  ' → 'hello'.",
    difficulty: 'medium',
  },
  {
    q: `What is the output?\nprint(3 == 3.0)`,
    o: { a: 'True', b: 'False', c: 'Error', d: 'None' },
    c: 0,
    ex: 'In Python, 3 (int) and 3.0 (float) have the same value, so == returns True.',
    difficulty: 'medium',
  },

  // ===== HARD (25 questions) =====
  {
    q: `What is the output?\nx = [1, 2, 3]\ny = x[:]\ny[0] = 99\nprint(x[0])`,
    o: { a: '1', b: '99', c: 'Error', d: 'None' },
    c: 0,
    ex: 'x[:] creates a shallow copy of the list. y is a separate copy, so modifying y does not affect x.',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\ndef func(a, b=[]):\n    b.append(a)\n    return b\nprint(func(1))\nprint(func(2))`,
    o: { a: '[1]\\n[1, 2]', b: '[1]\\n[2]', c: '[1]\\n[1]', d: 'Error' },
    c: 0,
    ex: 'Default arguments are evaluated only once at function definition. The same list is reused across calls, so b accumulates: [1] then [1, 2].',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nprint(list(filter(lambda x: x > 2, [1, 2, 3, 4])))`,
    o: { a: '[3, 4]', b: '[1, 2]', c: '[2, 3, 4]', d: '[4]' },
    c: 0,
    ex: 'filter() keeps elements where the lambda returns True. x > 2 is True for 3 and 4.',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nx = [1, 2, 3]\nfor i in range(len(x)):\n    x[i] += 1\nprint(x)`,
    o: { a: '[2, 3, 4]', b: '[1, 2, 3]', c: '[1, 2, 3, 1]', d: 'Error' },
    c: 0,
    ex: 'The loop increments each element by 1. [1, 2, 3] → [2, 3, 4].',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nprint({x: x**2 for x in range(3)})`,
    o: {
      a: '{0: 0, 1: 1, 2: 4}',
      b: '[0, 1, 4]',
      c: '{0: 0, 1: 1, 2: 4, 3: 9}',
      d: 'Error',
    },
    c: 0,
    ex: 'Dictionary comprehension: for x in 0, 1, 2, create key x with value x^2. Result: {0: 0, 1: 1, 2: 4}.',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\ndef outer(x):\n    def inner(y):\n        return x + y\n    return inner\nprint(outer(5)(3))`,
    o: { a: '8', b: '5', c: '3', d: 'Error' },
    c: 0,
    ex: 'outer(5) returns a closure inner that remembers x=5. Then inner(3) returns 5 + 3 = 8.',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nprint(1 if False else 2)`,
    o: { a: '2', b: '1', c: 'True', d: 'False' },
    c: 0,
    ex: 'Ternary expression: value_if_true if condition else value_if_false. Condition is False, so it returns 2.',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nx = [1, 2, 3, 4, 5]\nprint(x[1:4:2])`,
    o: { a: '[2, 4]', b: '[1, 3]', c: '[2, 3, 4]', d: '[1, 2, 3]' },
    c: 0,
    ex: 'Slicing with step: x[start:stop:step]. Start=1 (index 1=2), stop=4 (exclusive, index 4=5), step=2. Result: [2, 4].',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nprint(list(map(lambda x: x * 2, [1, 2, 3])))`,
    o: { a: '[2, 4, 6]', b: '[1, 2, 3]', c: '[1, 4, 9]', d: 'Error' },
    c: 0,
    ex: 'map() applies the lambda to each element. 1*2=2, 2*2=4, 3*2=6. Result: [2, 4, 6].',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\ntry:\n    x = 1 / 0\nexcept ZeroDivisionError:\n    print('error')\nfinally:\n    print('done')`,
    o: { a: 'error\\ndone', b: 'error', c: 'done', d: 'Error' },
    c: 0,
    ex: '1/0 raises ZeroDivisionError, caught by except block printing "error". The finally block always executes, printing "done".',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nprint(2 ** 3 ** 2)`,
    o: { a: '512', b: '64', c: '36', d: '12' },
    c: 0,
    ex: '** is right-associative. 2 ** 3 ** 2 = 2 ** (3 ** 2) = 2 ** 9 = 512.',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nclass A:\n    x = 1\nclass B(A):\n    pass\nprint(B.x)`,
    o: { a: '1', b: 'Error', c: 'None', d: '0' },
    c: 0,
    ex: 'B inherits from A, so B.x accesses the class attribute x defined in A. B.x = 1.',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nx = [1, 2, 3]\nprint(x * 2)`,
    o: {
      a: '[1, 2, 3, 1, 2, 3]',
      b: '[2, 4, 6]',
      c: '[1, 2, 3, 2]',
      d: 'Error',
    },
    c: 0,
    ex: 'Multiplying a list by an integer repeats the list. [1, 2, 3] * 2 = [1, 2, 3, 1, 2, 3].',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nprint(True == 1)`,
    o: { a: 'True', b: 'False', c: 'Error', d: 'None' },
    c: 0,
    ex: 'True is equal to 1 in value (bool is a subclass of int). True == 1 evaluates to True.',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nfrom functools import reduce\nprint(reduce(lambda a, b: a + b, [1, 2, 3, 4]))`,
    o: { a: '10', b: '24', c: '1234', d: 'Error' },
    c: 0,
    ex: 'reduce() cumulatively applies the lambda: (((1+2)+3)+4) = 10.',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nx = '123'\nprint(isinstance(x, int))`,
    o: { a: 'False', b: 'True', c: 'Error', d: 'None' },
    c: 0,
    ex: "isinstance() checks type. x is a string '123', not an int, so it returns False.",
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nprint(not not 1)`,
    o: { a: 'True', b: 'False', c: '1', d: 'Error' },
    c: 0,
    ex: 'not not 1 = not (False) = True. Double negation converts any truthy value to True.',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nprint(3 or 0 and 2)`,
    o: { a: '3', b: '0', c: '2', d: 'True' },
    c: 0,
    ex: 'and has higher precedence than or. 3 or (0 and 2) = 3 or 0 = 3 (short-circuits, returns first truthy).',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nx = [1, 2, 3]\nprint(x.remove(2))\nprint(x)`,
    o: {
      a: 'None\\n[1, 3]',
      b: '2\\n[1, 3]',
      c: '[1, 3]\\n[1, 3]',
      d: 'Error',
    },
    c: 0,
    ex: 'list.remove() modifies the list in-place and returns None. After removing 2, x becomes [1, 3].',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nprint(divmod(10, 3))`,
    o: { a: '(3, 1)', b: '(3, 0)', c: '3', d: '1' },
    c: 0,
    ex: 'divmod(a, b) returns a tuple (a // b, a % b). divmod(10, 3) = (3, 1).',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nprint(''.join(reversed('hello')))`,
    o: { a: 'olleh', b: 'hello', c: 'h', d: 'Error' },
    c: 0,
    ex: "reversed('hello') returns an iterator yielding 'o','l','l','e','h'. ''.join() concatenates them to 'olleh'.",
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nx = [1, 2, 3]\nprint(x.index(2))`,
    o: { a: '1', b: '2', c: '0', d: 'Error' },
    c: 0,
    ex: 'list.index(2) returns the index of the first occurrence of 2. In [1, 2, 3], 2 is at index 1.',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nprint(sorted([3, 1, 2], reverse=True))`,
    o: { a: '[3, 2, 1]', b: '[1, 2, 3]', c: '[3, 1, 2]', d: 'None' },
    c: 0,
    ex: 'sorted() returns a new sorted list. reverse=True sorts in descending order: [3, 2, 1].',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nprint(0.1 + 0.2 == 0.3)`,
    o: { a: 'False', b: 'True', c: 'Error', d: 'None' },
    c: 0,
    ex: 'Floating-point precision issue: 0.1 + 0.2 = 0.30000000000000004, which is not exactly 0.3.',
    difficulty: 'hard',
  },
  {
    q: `What is the output?\nprint(list(zip([1, 2], ['a', 'b'])))`,
    o: {
      a: "[(1, 'a'), (2, 'b')]",
      b: "[[1, 'a'], [2, 'b']]",
      c: "[1, 'a', 2, 'b']",
      d: 'Error',
    },
    c: 0,
    ex: "zip() pairs elements from multiple iterables. (1,'a') and (2,'b') are paired into tuples.",
    difficulty: 'hard',
  },

  // ===== NIGHTMARE (25 questions) =====
  {
    q: `What is the output?\nx = [1, 2, 3]\nfor i in x:\n    x.append(i + 3)\n    if len(x) > 5:\n        break\nprint(x)`,
    o: {
      a: '[1, 2, 3, 4, 5, 6]',
      b: '[1, 2, 3]',
      c: '[1, 2, 3, 4, 5]',
      d: 'Error',
    },
    c: 0,
    ex: 'The loop iterates over x while appending. i=1→append 4, i=2→append 5, i=3→append 6, len=6>5 break. Result: [1,2,3,4,5,6].',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\ndef gen():\n    yield 1\n    yield 2\n    yield 3\ng = gen()\nprint(list(zip(g, g)))`,
    o: {
      a: '[(1, 2)]',
      b: '[(1, 1), (2, 2), (3, 3)]',
      c: '[(1, 2), (3, None)]',
      d: '[(1, 2, 3)]',
    },
    c: 0,
    ex: 'zip(g, g) consumes the same generator. First call gets 1, second gets 2 → (1,2). Next call gets 3, but no more → stops. Result: [(1, 2)].',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint({True: 'yes', 1: 'no', 1.0: 'maybe'})`,
    o: {
      a: "{True: 'maybe'}",
      b: "{True: 'yes', 1: 'no', 1.0: 'maybe'}",
      c: "{1: 'no'}",
      d: 'Error',
    },
    c: 0,
    ex: 'True, 1, and 1.0 all hash to the same value. Each overwrites the previous. The last value assigned is "maybe".',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nclass A:\n    def __init__(self):\n        self.x = 1\n    def __eq__(self, other):\n        return self.x == other.x\na = A()\nb = A()\nprint(a == b)\nprint(a is b)`,
    o: {
      a: 'True\\nFalse',
      b: 'True\\nTrue',
      c: 'False\\nFalse',
      d: 'False\\nTrue',
    },
    c: 0,
    ex: 'a == b uses __eq__ which compares self.x (1 == 1) → True. a is b checks identity (different objects) → False.',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(1 < 2 == 2)`,
    o: { a: 'True', b: 'False', c: 'Error', d: 'None' },
    c: 0,
    ex: 'Python supports chained comparisons. 1 < 2 == 2 is equivalent to (1 < 2) and (2 == 2) → True and True → True.',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nx = [[]] * 3\nx[0].append(1)\nprint(x)`,
    o: {
      a: '[[1], [1], [1]]',
      b: '[[1], [], []]',
      c: '[[1], [1]]',
      d: 'Error',
    },
    c: 0,
    ex: '[[]] * 3 creates a list with 3 references to the SAME inner list. Modifying one affects all: [[1], [1], [1]].',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(all([]))`,
    o: { a: 'True', b: 'False', c: 'None', d: 'Error' },
    c: 0,
    ex: 'all() returns True for an empty iterable (vacuous truth - no elements to be falsy).',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(any([]))`,
    o: { a: 'False', b: 'True', c: 'None', d: 'Error' },
    c: 0,
    ex: 'any() returns False for an empty iterable (no elements to be truthy).',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nimport sys\nx = 'a' * 256\ny = 'a' * 256\nprint(x is y)`,
    o: { a: 'True', b: 'False', c: 'Error', d: 'None' },
    c: 0,
    ex: 'CPython interns short strings (usually < 4096 chars). "a"*256 is still short enough to be interned, so x and y reference the same object.',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\ndef func(a, b, c):\n    return a + b + c\nargs = (1, 2, 3)\nkwargs = {'c': 4, 'b': 5}\nprint(func(1, *args, **kwargs))`,
    o: { a: 'Error', b: '6', c: '10', d: '7' },
    c: 0,
    ex: "func(1, *args, **kwargs) expands to func(1, 1, 2, 3, c=4, b=5). 'a' gets 1, then *args provides 1,2,3 but 'a' already got 1, so 'b' gets 1, 'c' gets 2, then **kwargs tries to set 'c' and 'b' again → TypeError for duplicate arguments.",
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(0 or '' or None or 42)`,
    o: { a: '42', b: '0', c: "''", d: 'None' },
    c: 0,
    ex: 'or returns the first truthy value. 0, "", None are all falsy, so it returns 42 (the last truthy value).',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(42 and '' and 0)`,
    o: { a: "''", b: '42', c: '0', d: 'True' },
    c: 0,
    ex: 'and returns the first falsy value. 42 is truthy, then "" is falsy, so it returns "" (empty string).',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(3 * 3 ** 3)`,
    o: { a: '81', b: '27', c: '36', d: '9' },
    c: 0,
    ex: '** has higher precedence than *. 3 * 3 ** 3 = 3 * (3 ** 3) = 3 * 27 = 81.',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(1 == True == 1)`,
    o: { a: 'True', b: 'False', c: 'Error', d: 'None' },
    c: 0,
    ex: 'Chained comparison: (1 == True) and (True == 1). Both are True, so the result is True.',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(0 == False == 0)`,
    o: { a: 'True', b: 'False', c: 'Error', d: 'None' },
    c: 0,
    ex: 'Chained comparison: (0 == False) and (False == 0). Both are True, so the result is True.',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nx = [1, 2, 3]\nprint(x[5:])`,
    o: { a: '[]', b: 'Error', c: 'None', d: '[1, 2, 3]' },
    c: 0,
    ex: 'Slicing beyond the list bounds does not raise an error. x[5:] returns an empty list [].',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(0 ** 0)`,
    o: { a: '1', b: '0', c: 'Error', d: 'None' },
    c: 0,
    ex: 'In Python, 0 ** 0 = 1 by convention (mathematically defined as 1 for the empty product).',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(1.0 == 1)\nprint(1.0 is 1)`,
    o: {
      a: 'True\\nFalse',
      b: 'True\\nTrue',
      c: 'False\\nFalse',
      d: 'False\\nTrue',
    },
    c: 0,
    ex: '== compares value: 1.0 == 1 is True. "is" compares identity: 1.0 (float) and 1 (int) are different objects, so False.',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(1 < 2 > 1)`,
    o: { a: 'True', b: 'False', c: 'Error', d: 'None' },
    c: 0,
    ex: 'Chained comparison: (1 < 2) and (2 > 1) → True and True → True.',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(1 < 2 and 2 > 1)`,
    o: { a: 'True', b: 'False', c: 'Error', d: 'None' },
    c: 0,
    ex: '1 < 2 is True, 2 > 1 is True. True and True = True.',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(1 < 2 < 1)`,
    o: { a: 'False', b: 'True', c: 'Error', d: 'None' },
    c: 0,
    ex: 'Chained comparison: (1 < 2) and (2 < 1) → True and False → False.',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(1 < 2 and 2 < 1)`,
    o: { a: 'False', b: 'True', c: 'Error', d: 'None' },
    c: 0,
    ex: '1 < 2 is True, 2 < 1 is False. True and False = False.',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(1 < 2 == 2 > 1)`,
    o: { a: 'True', b: 'False', c: 'Error', d: 'None' },
    c: 0,
    ex: 'Chained: (1 < 2) and (2 == 2) and (2 > 1) → True and True and True → True.',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(1 < 2 == 2 > 1 == True)`,
    o: { a: 'True', b: 'False', c: 'Error', d: 'None' },
    c: 0,
    ex: 'Chained: (1 < 2) and (2 == 2) and (2 > 1) and (1 == True) → all True → True.',
    difficulty: 'nightmare',
  },
  {
    q: `What is the output?\nprint(1 < 2 == 2 > 1 == True == 1)`,
    o: { a: 'True', b: 'False', c: 'Error', d: 'None' },
    c: 0,
    ex: 'Chained: (1 < 2) and (2 == 2) and (2 > 1) and (1 == True) and (True == 1) → all True → True.',
    difficulty: 'nightmare',
  },
];
